import os
import time

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    CollectorRegistry,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)


REQUEST_COUNT = Counter(
    "apptrail_http_requests_total",
    "Total HTTP requests processed by AppTrail.",
    ["method", "path", "status_code"],
)
REQUEST_LATENCY = Histogram(
    "apptrail_http_request_duration_seconds",
    "HTTP request latency in seconds.",
    ["method", "path"],
)
REQUESTS_IN_PROGRESS = Gauge(
    "apptrail_http_requests_in_progress",
    "In-flight HTTP requests.",
)
AI_TASK_RUNS = Counter(
    "apptrail_ai_task_runs_total",
    "Total AI task runs by task/model/outcome.",
    ["task", "model", "outcome"],
)
AI_TASK_DURATION = Histogram(
    "apptrail_ai_task_duration_seconds",
    "AI task duration in seconds.",
    ["task", "model", "outcome"],
)
AI_TASK_FALLBACKS = Counter(
    "apptrail_ai_task_fallbacks_total",
    "Total AI task fallbacks by task and reason.",
    ["task", "reason"],
)
RESEARCH_RUNS = Counter(
    "apptrail_research_runs_total",
    "Total Radar research runs by mode, trigger, and outcome.",
    ["mode", "trigger", "outcome"],
)
RESEARCH_RUN_DURATION = Histogram(
    "apptrail_research_run_duration_seconds",
    "Radar research run duration in seconds.",
    ["mode", "trigger", "outcome"],
)
RESEARCH_RUN_STEP_DURATION = Histogram(
    "apptrail_research_run_step_duration_seconds",
    "Radar research step duration in seconds.",
    ["mode", "step_name", "outcome"],
)
RESEARCH_RUN_FAILURES = Counter(
    "apptrail_research_run_failures_total",
    "Total Radar research run failures by mode and step.",
    ["mode", "step_name"],
)
RESEARCH_REPORTS_GENERATED = Counter(
    "apptrail_research_reports_generated_total",
    "Total Radar research reports generated by mode and status.",
    ["mode", "status"],
)
RESEARCH_SOURCES_FETCHED = Counter(
    "apptrail_research_sources_fetched_total",
    "Total Radar research sources fetched by mode and source type.",
    ["mode", "source_type"],
)
RESEARCH_EVIDENCE_ITEMS = Counter(
    "apptrail_research_evidence_items_total",
    "Total Radar research evidence items produced by mode and evidence type.",
    ["mode", "evidence_type"],
)
JOB_SOURCE_DISCOVERED = Counter(
    "apptrail_job_source_discovered_total",
    "Total job sources discovered by provider, discovery surface, and status.",
    ["provider_type", "discovered_from", "status"],
)
JOB_SOURCE_VERIFIED = Counter(
    "apptrail_job_source_verified_total",
    "Total job source verification attempts by provider and status.",
    ["provider_type", "status"],
)
JOB_SOURCE_FETCH_DURATION = Histogram(
    "apptrail_job_source_fetch_duration_seconds",
    "Job source verification duration in seconds by provider.",
    ["provider_type"],
)
JOB_SOURCE_FETCH_ERRORS = Counter(
    "apptrail_job_source_fetch_errors_total",
    "Job source verification errors by provider and error type.",
    ["provider_type", "error_type"],
)
JOB_SEARCH_REQUESTS = Counter(
    "apptrail_job_search_requests_total",
    "Job search requests by source mode.",
    ["mode"],
)
JOB_SEARCH_RESULTS = Counter(
    "apptrail_job_search_results_total",
    "Job search results returned by source type.",
    ["source_type"],
)
JOB_SEARCH_BROAD_API_CALLS = Counter(
    "apptrail_job_search_broad_api_calls_total",
    "Broad job-search provider API calls.",
    ["provider"],
)
JOB_SEARCH_BROAD_API_CALLS_AVOIDED = Counter(
    "apptrail_job_search_broad_api_calls_avoided_total",
    "Broad provider API calls avoided by direct source search.",
    ["reason"],
)
PRIVATE_URL_REJECTED = Counter(
    "apptrail_private_url_rejected_total",
    "Private URL classifications rejected from shared source intelligence.",
    ["rule_id"],
)
SOURCE_REVIEW_QUEUE_SIZE = Gauge(
    "apptrail_source_review_queue_size",
    "Current source review queue size by reason.",
    ["reason"],
)


def metrics_payload() -> bytes:
    if os.getenv("PROMETHEUS_MULTIPROC_DIR"):
        from prometheus_client import multiprocess

        registry = CollectorRegistry()
        multiprocess.MultiProcessCollector(registry)
        return generate_latest(registry)
    return generate_latest()


def metrics_headers() -> dict[str, str]:
    return {"Content-Type": CONTENT_TYPE_LATEST}


def observe_request(method: str, path: str, status_code: int, started_at: float) -> None:
    duration = time.perf_counter() - started_at
    REQUEST_COUNT.labels(method=method, path=path, status_code=str(status_code)).inc()
    REQUEST_LATENCY.labels(method=method, path=path).observe(duration)


def observe_ai_task(task: str, model: str, outcome: str, duration_seconds: float) -> None:
    AI_TASK_RUNS.labels(task=task, model=model, outcome=outcome).inc()
    AI_TASK_DURATION.labels(task=task, model=model, outcome=outcome).observe(duration_seconds)


def observe_ai_fallback(task: str, reason: str) -> None:
    AI_TASK_FALLBACKS.labels(task=task, reason=reason).inc()


def observe_research_run(
    *,
    mode: str | None,
    trigger: str | None,
    outcome: str | None,
    duration_seconds: float,
) -> None:
    mode_label = mode or "unknown"
    trigger_label = trigger or "unknown"
    outcome_label = outcome or "unknown"
    RESEARCH_RUNS.labels(mode=mode_label, trigger=trigger_label, outcome=outcome_label).inc()
    RESEARCH_RUN_DURATION.labels(
        mode=mode_label,
        trigger=trigger_label,
        outcome=outcome_label,
    ).observe(max(duration_seconds, 0.0))


def observe_research_step(
    *,
    mode: str | None,
    step_name: str | None,
    outcome: str | None,
    duration_seconds: float,
) -> None:
    RESEARCH_RUN_STEP_DURATION.labels(
        mode=mode or "unknown",
        step_name=step_name or "unknown",
        outcome=outcome or "unknown",
    ).observe(max(duration_seconds, 0.0))


def observe_research_failure(*, mode: str | None, step_name: str | None) -> None:
    RESEARCH_RUN_FAILURES.labels(mode=mode or "unknown", step_name=step_name or "unknown").inc()


def observe_research_report_generated(*, mode: str | None, status: str | None, count: int = 1) -> None:
    RESEARCH_REPORTS_GENERATED.labels(mode=mode or "unknown", status=status or "unknown").inc(max(count, 0))


def observe_research_sources_fetched(*, mode: str | None, source_type: str | None, count: int = 1) -> None:
    RESEARCH_SOURCES_FETCHED.labels(mode=mode or "unknown", source_type=source_type or "unknown").inc(max(count, 0))


def observe_research_evidence_items(*, mode: str | None, evidence_type: str | None, count: int = 1) -> None:
    RESEARCH_EVIDENCE_ITEMS.labels(mode=mode or "unknown", evidence_type=evidence_type or "unknown").inc(max(count, 0))


def observe_job_source_discovered(*, provider_type: str | None, discovered_from: str | None, status: str | None) -> None:
    JOB_SOURCE_DISCOVERED.labels(
        provider_type=provider_type or "unknown",
        discovered_from=discovered_from or "unknown",
        status=status or "unknown",
    ).inc()


def observe_job_source_verified(*, provider_type: str | None, status: str | None, duration_seconds: float, error_type: str | None = None) -> None:
    provider = provider_type or "unknown"
    JOB_SOURCE_VERIFIED.labels(provider_type=provider, status=status or "unknown").inc()
    JOB_SOURCE_FETCH_DURATION.labels(provider_type=provider).observe(max(duration_seconds, 0.0))
    if error_type:
        JOB_SOURCE_FETCH_ERRORS.labels(provider_type=provider, error_type=error_type).inc()


def observe_job_search_request(*, mode: str | None) -> None:
    JOB_SEARCH_REQUESTS.labels(mode=mode or "unknown").inc()


def observe_job_search_results(*, source_type: str | None, count: int = 1) -> None:
    JOB_SEARCH_RESULTS.labels(source_type=source_type or "unknown").inc(max(count, 0))


def observe_job_search_broad_api_call(*, provider: str | None) -> None:
    JOB_SEARCH_BROAD_API_CALLS.labels(provider=provider or "unknown").inc()


def observe_job_search_broad_api_call_avoided(*, reason: str | None) -> None:
    JOB_SEARCH_BROAD_API_CALLS_AVOIDED.labels(reason=reason or "unknown").inc()


def observe_private_url_rejected(*, rule_id: str | None) -> None:
    PRIVATE_URL_REJECTED.labels(rule_id=rule_id or "unknown").inc()


def set_source_review_queue_size(*, reason: str | None, value: int) -> None:
    SOURCE_REVIEW_QUEUE_SIZE.labels(reason=reason or "unknown").set(max(value, 0))
