#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_ENV="${1:-$ROOT_DIR/.env.local}"

if [[ -f "$TARGET_ENV" ]]; then
  echo "$TARGET_ENV already exists."
  echo "Move it out of the way or pass a different target path if you want a fresh local-only env file."
  exit 1
fi

JWT_SECRET="$(python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
)"

GMAIL_TOKEN_KEY="$(python3 - <<'PY'
import base64
import os
print(base64.urlsafe_b64encode(os.urandom(32)).decode())
PY
)"

cat > "$TARGET_ENV" <<EOF
# AppTrail local-only environment
# Generated by scripts/setup_local_env.sh

ENVIRONMENT=development
LOCAL_DEV_AUTH=1

BACKEND_HOST=0.0.0.0
BACKEND_PORT=8000
DASHBOARD_URL=http://localhost:3000

DATABASE_URL=postgresql+asyncpg://apptrail:apptrail@localhost:5432/apptrail
REDIS_URL=redis://localhost:6379/0

READINESS_REQUIRE_CELERY=false
HEALTH_CHECK_DATABASE=false
HEALTH_CHECK_REDIS=false
SCHEDULED_DB_JOBS_ENABLED=false
GMAIL_POLLING_ENABLED=false
JOB_SOURCE_VERIFICATION_BEAT_ENABLED=false
RADAR_ENABLED=false
RADAR_RESEARCH_ENABLED=false

JWT_SECRET=$JWT_SECRET
APPTRAIL_GMAIL_TOKEN_ENCRYPTION_KEY=$GMAIL_TOKEN_KEY

GOOGLE_REDIRECT_URI=http://localhost:8000/api/auth/google/callback
GMAIL_REDIRECT_URI=http://localhost:8000/api/auth/gmail/callback

# Optional local-dev identity override for the "Continue locally" button.
LOCAL_DEV_AUTH_EMAIL=me@apptrail.local
LOCAL_DEV_AUTH_NAME="Local AppTrail User"

# Optional paid or third-party integrations. Leave blank to disable.
OPENAI_API_KEY=
GMAIL_CLIENT_ID=
GMAIL_CLIENT_SECRET=
HUNTER_API_KEY=
SERPAPI_KEY=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=

LOG_LEVEL=INFO
SQLALCHEMY_ECHO=false
PLAYWRIGHT_HEADLESS=true
GMAIL_CLASSIFIER_MODE=hybrid_dry_run
EOF

echo "Created $TARGET_ENV"
echo "Next steps:"
echo "  1. Fill in any optional API keys you want to use."
echo "  2. Run: make local-up"
echo "  3. Open: http://localhost:3000"
